spring.application.name=orderservice

spring.datasource.url=jdbc:postgresql://localhost:5432/order_db
spring.datasource.username=postgres
spring.datasource.password=postgre
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jpa.hibernate.ddl-auto=none
jpa.hibernate.show-sql=true
spring.liquibase.change-log=db.changelog/db.changelog-master.xml